name: beer_app
description: BME Flutter course homework project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: 5.0.3
  intl: 0.18.0
  get_it: 7.2.0
  go_router: 6.4.1
  json_annotation: 4.8.0

  firebase_core: 2.13.0
  firebase_crashlytics: 3.1.0
  firebase_messaging: 14.6.1
  cloud_firestore: 4.7.1

  device_info_plus: 8.1.0
  package_info_plus: 3.0.3
  cached_network_image: 3.2.3
  collection: 1.17.1
  provider: 6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  flutter_lints: 2.0.1
  json_serializable: 6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/2.0x/
    - assets/img/3.0x/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Black.ttf
          weight: 900