// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJ2a3dgguwut3D27paLlCdF8XFUnTAOI',
    appId: '1:701463645222:web:8dbd07d5286fbfa9bcaae7',
    messagingSenderId: '701463645222',
    projectId: 'beerapp-421f7',
    authDomain: 'beerapp-421f7.firebaseapp.com',
    storageBucket: 'beerapp-421f7.appspot.com',
    measurementId: 'G-DL38NFCXE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9vLRN_X1Bp31F567ANlz3Qh-yzNlNy8',
    appId: '1:701463645222:android:360348b23c3059f5bcaae7',
    messagingSenderId: '701463645222',
    projectId: 'beerapp-421f7',
    storageBucket: 'beerapp-421f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxG5SajoVuVatPTXrKlyMNNKQY6nA1YQ',
    appId: '1:701463645222:ios:6850901f24020b52bcaae7',
    messagingSenderId: '701463645222',
    projectId: 'beerapp-421f7',
    storageBucket: 'beerapp-421f7.appspot.com',
    iosClientId: '701463645222-uo9dvb9ordarrbt2trojam19t2v6p102.apps.googleusercontent.com',
    iosBundleId: 'com.example.beerRating',
  );
}
